Atom only has one character set
I was getting some linker errors with apple clang. "Undefined reference to Utils::detail::Table<5ul>::to". I wasn't able to reproduce the error with compiler explorer. Latest GCC and Clang worked fine. It's a real shame apple clang failed. I had to make this change to get it to link properly.